apiVersion: v1
kind: Service
metadata:
  name: server-health-api-service
spec:
  selector:
    app: server-health-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer